### ISSUE TITLE
逃~

### ISSUE THREAD

**Issue by yetone** [messense/is-minified-js#1]
https://github.com/messense/is-minified-js/blob/master/is_minified_js/__init__.py#L3

`__all__` 只能用 list 🌝

**Comment by messense** [comment]
写 `__all__` 只是为了避免 flake8 的 lint ...

**Comment by yetone** [comment]
@messense 可以 `# noqa` 啊 =。=

**Comment by messense** [comment]
就是不想写 `# noqa` 看起来不爽啊。
